### ISSUE TITLE
2022 branch - Table is inactive

### ISSUE THREAD

**Issue by jrodriguez-rc** [SAP-samples/cloud-abap-rap#19]
I'm trying to create a new project, in a package defined as "ABAP for Cloud Development" but it fails because it determines that the table is not active
![image](https://user-images.githubusercontent.com/56556686/234520669-69d10071-48ce-498c-b7eb-b22157e4df0e.png)

The table is active, but XCO determines the table doesn't exist
<img width="720" alt="image" src="https://user-images.githubusercontent.com/56556686/234521286-cab3c4d3-394e-49bc-bf06-3f826ed1a24d.png">

This is because XCO is applying a filter to check if the table is released
<img width="947" alt="image" src="https://user-images.githubusercontent.com/56556686/234522171-6713c05d-490f-4bea-a8b6-5e5b7cfc01c3.png">

**Comment by anfisc** [comment]
Hi Jaime,
thanks for pointing me to this issue.
I have to change the logic of my generator. Currently it checks the language version of the package and as a result use the xco library version for either cloud or on prem. 
I have however to change this because the cloud version should only be used if the package is also member of a software component that has also language version 5. 
Since the cloud version of the xco library is only able to "see" the objects within the same software component the call currently fails. 
As a workaround you can change the language version of your package to "abap_standard".
But I have to perform additional checks what such a change to my code means when it comes to generation of objects.
Kind regards,
Andre
